### ISSUE TITLE
Typo in `CHARGE_VOLTAGE` register field

### ISSUE THREAD

**Issue by felipebalbi** [OpenDevicePartnership/bq25773#5]
```yaml
CHARGE_VOLTAGE:
  type: register
  address: 0x04
  size_bits: 16
  reset_value: 0x0000
  fields:
    CHARGE_CURRENT:
      base: uint
      start: 2
      end: 15
      description:  Charge voltage setting.
```

The field should be `CHARGE_VOLTAGE` or, maybe, just `VOLTAGE`
